"""OpsPilot - Evidence-Grounded Incident Diagnosis

Main Streamlit application entry point.
"""

import streamlit as st

from src.opspilot.config import get_config


def main():
    """Render the OpsPilot landing page."""
    config = get_config()

    st.set_page_config(
        page_title="OpsPilot",
        page_icon="🔍",
        layout="wide"
    )

    st.title("🔍 OpsPilot")
    st.subheader("Evidence-Grounded Incident Diagnosis")

    st.markdown("""
    **OpsPilot** is an intelligent agent system designed to assist DevOps teams in
    diagnosing software incidents by analyzing:

    - 📝 Incident descriptions
    - 📊 Application logs
    - 📚 Operational runbooks

    The system uses evidence-grounded reasoning to provide actionable insights and
    remediation suggestions based on your organization's best practices.
    """)

    mode = config.opspilot_mode.upper()
    if mode == "DEMO":
        st.info("🎭 **Demo Mode**: Running with simulated data and scenarios")
    else:
        st.success("🚀 **Live Mode**: Connected to OpenAI API")

    st.warning("""
    ⚠️ **Safety Notice**: All remediation recommendations generated by OpsPilot
    require human review before implementation. Always validate suggestions against
    your specific environment and follow your organization's change management procedures.
    """)

    st.markdown("---")
    st.markdown("*Project Status: Initial Development Phase*")


if __name__ == "__main__":
    main()
